### ISSUE TITLE
Any issues with using the original Vue SFC Playground?

### ISSUE THREAD

**Issue by fardolieri** [wheatjs/vueuse-playground#10]
Is there any reason not use the original Vue SFC Playground [https://sfc.vuejs.org/#](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHVzZU1vdXNlIH0gZnJvbSAnQHZ1ZXVzZS9jb3JlJ1xuaW1wb3J0IENvb3JkaW5hdGUgZnJvbSAnLi9Db29yZGluYXRlLnZ1ZSdcblxuY29uc3QgeyB4LCB5IH0gPSB1c2VNb3VzZSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdlxuICBncmlkPVwifiBmbG93LWNvbCBnYXAtNFwiXG4gIHBsYWNlPVwiY29udGVudC1jZW50ZXIgaXRlbXMtY2VudGVyXCJcbiAgaD1cInNjcmVlblwiXG4gIGZvbnQ9XCJtb25vXCJcbiAgPlxuICA8Q29vcmRpbmF0ZSBsYWJlbD1cIlhcIiA6dmFsdWU9XCJ4XCIgLz5cbiAgPENvb3JkaW5hdGUgbGFiZWw9XCJZXCIgOnZhbHVlPVwieVwiIC8+XG48L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWV1c2UvY29yZS9pbmRleC5tanNcIixcbiAgICBcIkB2dWV1c2Uvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVldXNlL3NoYXJlZC9pbmRleC5tanNcIixcbiAgICBcInZ1ZS1kZW1pXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS92dWUtZGVtaS9saWIvaW5kZXgubWpzXCJcbiAgfVxufSIsIkNvb3JkaW5hdGUudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IGRlZmluZVByb3BzIH0gZnJvbSAndnVlJ1xuXG5kZWZpbmVQcm9wcyh7XG4gIGxhYmVsOiBTdHJpbmcsXG4gIHZhbHVlOiBOdW1iZXIsXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxkaXZcbiAgZm9udD1cIm1vbm9cIlxuICBiZz1cImxpZ2h0LTUwMCBkYXJrOmRhcmstNTAwXCJcbiAgZmxleD1cIn4gY29sXCJcbiAgdGV4dD1cImNlbnRlclwiXG4gIHA9XCIyXCJcbiAgYm9yZGVyPVwicm91bmRlZFwiXG4+XG4gIDxzcGFuIHRleHQ9XCI0eGxcIj57eyB2YWx1ZSB9fTwvc3Bhbj5cbiAgPHNwYW4gdGV4dD1cInNtIGRhcms6bGlnaHQtOTAwIGRhcms6b3BhY2l0eS01MFwiIG09XCJ0LTJcIj5Nb3VzZSB7eyBsYWJlbCB9fTwvc3Bhbj5cbjwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==) with `@vueuse/core`, `@vueuse/shared` and `vue-demi` added to the `import-map.json`? It seems to work just fine.

**Comment by wheatjs** [comment]
The original Vue SFC playground works just fine. Although there is an update coming out for this playground that will add a lot of nice to have features. In the end it will come down to personal preference.

**Comment by WORMSS** [comment]
@fardolieri can I ask what settings you used in the sfc.vuejs playground?
I used `https://unpkg.com/@vueuse/shared` and `https://unpkg.com/@vueuse/core`  but unsure what to use for vue-demi at all. 
and I am not even sure the above for shared and core would work at all..

**Comment by fardolieri** [comment]
Sure, you can check out my settings by clicking the link [https://sfc.vuejs.org/#eyJBcHAud...](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHVzZU1vdXNlIH0gZnJvbSAnQHZ1ZXVzZS9jb3JlJ1xuaW1wb3J0IENvb3JkaW5hdGUgZnJvbSAnLi9Db29yZGluYXRlLnZ1ZSdcblxuY29uc3QgeyB4LCB5IH0gPSB1c2VNb3VzZSgpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdlxuICBncmlkPVwifiBmbG93LWNvbCBnYXAtNFwiXG4gIHBsYWNlPVwiY29udGVudC1jZW50ZXIgaXRlbXMtY2VudGVyXCJcbiAgaD1cInNjcmVlblwiXG4gIGZvbnQ9XCJtb25vXCJcbiAgPlxuICA8Q29vcmRpbmF0ZSBsYWJlbD1cIlhcIiA6dmFsdWU9XCJ4XCIgLz5cbiAgPENvb3JkaW5hdGUgbGFiZWw9XCJZXCIgOnZhbHVlPVwieVwiIC8+XG48L2Rpdj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVldXNlL2NvcmVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWV1c2UvY29yZS9pbmRleC5tanNcIixcbiAgICBcIkB2dWV1c2Uvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVldXNlL3NoYXJlZC9pbmRleC5tanNcIixcbiAgICBcInZ1ZS1kZW1pXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS92dWUtZGVtaS9saWIvaW5kZXgubWpzXCJcbiAgfVxufSIsIkNvb3JkaW5hdGUudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IGRlZmluZVByb3BzIH0gZnJvbSAndnVlJ1xuXG5kZWZpbmVQcm9wcyh7XG4gIGxhYmVsOiBTdHJpbmcsXG4gIHZhbHVlOiBOdW1iZXIsXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxkaXZcbiAgZm9udD1cIm1vbm9cIlxuICBiZz1cImxpZ2h0LTUwMCBkYXJrOmRhcmstNTAwXCJcbiAgZmxleD1cIn4gY29sXCJcbiAgdGV4dD1cImNlbnRlclwiXG4gIHA9XCIyXCJcbiAgYm9yZGVyPVwicm91bmRlZFwiXG4+XG4gIDxzcGFuIHRleHQ9XCI0eGxcIj57eyB2YWx1ZSB9fTwvc3Bhbj5cbiAgPHNwYW4gdGV4dD1cInNtIGRhcms6bGlnaHQtOTAwIGRhcms6b3BhY2l0eS01MFwiIG09XCJ0LTJcIj5Nb3VzZSB7eyBsYWJlbCB9fTwvc3Bhbj5cbjwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==) and then see *Import Map* in the top right corner, where the files are.

My settings were
```json
{
  "imports": {
    "vue": "https://sfc.vuejs.org/vue.runtime.esm-browser.js",
    "@vueuse/core": "https://cdn.jsdelivr.net/npm/@vueuse/core/index.mjs",
    "@vueuse/shared": "https://cdn.jsdelivr.net/npm/@vueuse/shared/index.mjs",
    "vue-demi": "https://cdn.jsdelivr.net/npm/vue-demi/lib/index.mjs",
    "vue/server-renderer": "https://sfc.vuejs.org/server-renderer.esm-browser.js"
  }
}
```

**Comment by WORMSS** [comment]
Thank you, this will help greatly when doing mini experiments as we migrate from Vue2 to Vue3 as I can send my team snippets of the VueUse library. Thank you.
