### ISSUE TITLE
Request to add a LICENSE file

### ISSUE THREAD

**Issue by rohitk-singh** [wheatjs/vueuse-playground#25]
Hi @wheatjs! Thanks for creating such beautiful vueuse playground! It made getting started and learning Vue and Vueuse exponentially easier for me!

Would you kindly consider adding a license file for this? I wanted to build upon this project for making a front-end for my custom disassembler and assembler project.

**Comment by wheatjs** [comment]
Done https://github.com/wheatjs/vueuse-playground/blob/main/LICENSE

Good luck on your project, I'd love to see it when it is done!

**Comment by rohitk-singh** [comment]
Thanks so much! I'm also excited for the project :)
