### ISSUE TITLE
这是哪种技术 感谢

### ISSUE THREAD

**Issue by zhangenming** [wheatjs/vueuse-playground#4]
![image](https://user-images.githubusercontent.com/21235555/121474922-5845b300-c9f7-11eb-851c-b2f7fa393f3e.png)

这些是什么东西啊 好奇怪 第一次遇到这种技术  谢谢
是那个windicss吗  去官方看了看好像也不太一样

**Comment by wheatjs** [comment]
This is attributify mode in windicss https://windicss.org/posts/attributify.html

**Comment by zhangenming** [comment]
thanks you...
sorry about use Chinese, I mistook you for a Chinese

**Comment by wheatjs** [comment]
No problem 😄
